- id: doi:10.1109/BIBM49941.2020.9313428
  image: ../images/he.png
  tags:
    - histopathology image
    - image transformation
    - image segmentation
    - unlabeled data
  publisher: IEEE BIBM

- id: doi:10.1109/CBMS49503.2020.00069
  image: ../images/cbms.png
  tags:
    - cell tracking
  publisher: IEEE CBMS

- id: doi:https://doi.org/10.1101/491035
  image: https://www.allencell.org/uploads/8/1/9/9/81996008/icon-segmenter2_orig.png
  extra-links:
    - type: website
      link: https://www.allencell.org/segmenter.html
    - type: source
      link: https://github.com/AllenCell/aics-ml-segmentation
      text: ML segmentation source
    - type: source
      link: https://github.com/AllenCell/aics-segmentation
      text: classic segmentation source
  tags:
    - image segmentation
    - 3D
    - tool
  publisher: bioRxiv

- id: doi:10.1109/ISBI.2019.8759430
  image: ../images/isbi.png
  tags:
    - image segmentation
    - 3D
  publisher: IEEE ISBI

- id: doi:https://doi.org/10.1609/aaai.v33i01.33015901
  image: ../images/aaai.png
  tags:
    - image segmentation
    - efficient annotation
  publisher: AAAI

- id: doi:10.1109/ISBI.2018.8363724
  image: ../images/isbi.png
  tags:
    - image registration
  publisher: IEEE ISBI
    
- id: doi:https://doi.org/10.1007/978-3-319-66185-8_3
  image: ../images/MICCAI.png
  tags:
    - image segmentation
  publisher: MICCAI

- id: doi:https://doi.org/10.1016/j.cels.2021.05.001
  image: https://www.allencell.org/uploads/8/1/9/9/81996008/cellsystems-cover-fish-aics-cos-2-final-thumb_2.png
  tags:
    - caridomyocyte
    - analysis and modeling
    - image segmentation

- id: url:https://papers.nips.cc/paper/2016/hash/4dcf435435894a4d0972046fc566af76-Abstract.html
  title: Combining Fully Convolutional and Recurrent Neural Networks for 3D Biomedical Image Segmentation
  authors:
    - J. Chen
    - L. Yang
    - Y. Zhang
    - M. Alber
    - D. Chen
  publisher: NeurIPS
  date: '2016-12-05'
  link: https://proceedings.neurips.cc/paper/2016/file/4dcf435435894a4d0972046fc566af76-Paper.pdf
  image: ../images/nips.png
  tags:
    - recurrent neural network
    - image segmentation

- id: doi:10.1128/JB.00184-19
  image: https://journals.asm.org/cms/10.1128/JB.00184-19/asset/1a011f2b-63f1-4345-b9b7-c2046a493bfc/assets/graphic/jb.00184-19-f0003.jpeg
  tags:
    - cell tracking
    - analysis and modeling
    - bacteria

- id: doi:10.1016/j.bpj.2019.01.007
  image: https://marlin-prod.literatumonline.com/cms/attachment/aa948b9d-5119-43c5-8bd7-a12cc5331c0d/gr4.jpg
  tags:
    - image registration
    - analysis and modeling

- id: doi:10.1016/j.matbio.2016.10.007
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0945053X16302517-gr8.sml
  tags:
    - image segmentation
    - analysis and modeling

- id: doi:10.1109/TMI.2016.2548490
  image: ../images/myxo.png
  tags:
    - image segmentation
    - cell tracking
  publisher: IEEE Transactions on Medical Imaging

- id: doi:10.1103/PhysRevLett.117.028301
  image: https://journals.aps.org/prl/article/10.1103/PhysRevLett.117.028301/figures/2/thumbnail
  tags:
    - analysis and modeling

- id: doi:10.1109/TIFS.2016.2535901
  image: ../images/iris.png
  tags:
    - human-in-the-loop
    - image recognition
    - forensics

- id: doi:https://doi.org/10.1007/978-3-319-66179-7_46
  image: ../images/MICCAI.png
  tags:
    - image segmentation
    - human-in-the-loop
  publisher: MICCAI

- id: doi:https://doi.org/10.1007/978-3-319-66179-7_47
  image: ../images/MICCAI.png
  tags:
    - image segmentation
    - unlabeled data
  publisher: MICCAI

- id: doi:https://doi.org/10.1145/3061639.3062297
  image: ../images/gpu.png
  tags:
    - hardware/software co-design
  publisher: ACM Design Automation Conference

- id: doi:10.1109/ISBI.2016.7493426
  image: ../images/pseudo.png
  tags:
    - image segmentation
    - cell tracking
  publisher: IEEE ISBI

- id: doi:https://doi.org/10.1007/978-3-319-24574-4_34
  image: ../images/MICCAI.png
  tags:
    - image segmentation
    - cell tracking
  publisher: MICCAI
    
- id: doi:10.1109/ISBA.2015.7126352
  image: ../images/iris.png
  tags:
    - human-in-the-loop
    - image recognition
    - forensics
  publisher: IEEE International Conference on Identity, Security, and Behavior Analysis
    
- id: doi:https://doi.org/10.1007/978-3-319-10470-6_15
  image: ../images/MICCAI.png
  tags:
    - cell tracking
  publisher: MICCAI

- id: doi:10.1109/CBMS.2014.62
  image: ../images/fibrin.png
  tags:
    - image segmentation
  publisher: IEEE CBMS

    