name: Auto Scraper

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install beautifulsoup4
      run: pip install requests beautifulsoup4

    - name: Run Scraper
      run: python scripts/scrape_scholar.py
